import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const oneShot = prod || (process.argv[2] === 'dev');

const prodBanner = prod ? 'console.debug = function() {};\n' : '';

const context = await esbuild.context({
  banner: {
    js: banner + prodBanner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  loader: {
    '.tsx': 'tsx',
    '.jsx': 'jsx',
    // Inline binary assets as data URIs so they ship inside main.js
    // (Obsidian plugins don't ship loose asset files; esbuild bundles them).
    '.png': 'dataurl',
    '.svg': 'dataurl',
    '.jpg': 'dataurl',
    '.jpeg': 'dataurl',
    '.gif': 'dataurl',
    '.webp': 'dataurl',
  },
  jsx: 'automatic',
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (oneShot) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}